baseURL = "http://thehillsoundstudio.com"
languagecode = "en-us"
title = "The Hill Sound Studio"
[params]
  description = "The Hill Sound Studio is a full service Audio Production company based in Prince Edward Island, Canada."
  author = "Adam Gallant"
