baseurl = "http://thehillsoundstudio.com"
languagecode = "en-us"
pluralizelisttitles = false
title = "The Hill Sound Studio"
[indexes]
tag = "tags"
[[menu.main]]
name = "Clientelle"
url = "/clients"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
description = "The Hill Sound Studio is a full service Audio Production company based in Prince Edward Island, Canada."
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
