---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
  blog:
    default_front_matter_template: blog
upload_dir: static/forestryio/images
public_path: "/forestryio/images"
front_matter_path: "/forestryio/images"
use_front_matter_path: false
file_template: ":filename:"
version: '0.17'
