---
upload_path: "/static/forestryio/images"
frontmatter_file_url_template: "/forestryio/images"
body_file_url_template: "/forestryio/images"
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
  blog:
    default_front_matter_template: blog
version: '0.17'
