---
label: default
hide_body: false
fields:
- name: title
  default: ''
  label: Title
  hidden: false
  type: text
- name: date
  default: ''
  label: Date
  hidden: false
  type: datetime
- name: draft
  default: false
  label: Draft
  hidden: false
  type: boolean
- type: file
  name: image
  label: Image
pages:
- content/content/equipment.md
- content/content/about-us.md
